main: games.aternos.odessa.gameapi.GameApi
name: OdessaGameApi
version: 1
description: It runs stuff
authors: [_Bot_, Aternos]
website: aternos.games
commands:
  setlobbyspawn:
    description: Set Lobby Spawn
    usage: /command
