main: games.aternos.odessa.gameapi.GameApi
name: OdessaGameApi
version: 1
description: It runs stuff
authors: [_Bot_, Aternos]
website: aternos.games
commands:
  odessa:
    description: Odessa Super Command
    usage: /command <args>
  setlobbyspawn:
    description: Set Lobby Spawn
    usage: /command
  createarena:
    description: CreateArena
    usage: /command <name> <author>
  addarenaspawn:
    description: AddSpawn
    usage: /command <mapname> <int> <int>
